### ISSUE TITLE
Could the docker container hundle update using the build in updater?

### ISSUE THREAD

**Issue by LunarstarFurry** [NetLah/docker-crushftp#6]
Just wondering if it's even possible to update it using to build in updater.

Tried to do a few update there but it always seems to just restart with the same version.

Or do I need to wait for docker container to update the version?

**Comment by thohng** [comment]
Hi @LunarstarPony , on the Admin UI, you can trigger the update, after restart CrushFTP will be the new version. The only not update this time is the Java runtime and docker OS image (Alpine 3.13.6)

> Or do I need to wait for docker container to update the version?

We only build new container when new minor version coming, for keep track only, such as 10.3.0 -> 10.4.0 -> 10.5.

**Comment by LunarstarFurry** [comment]
Oh Alright Thx!
